export * from "./Create";
export * from "./Read";
export * from "./Remove";
export * from "./Update";
export * from "./CrearE";
export * from "./ReadE";
export * from "./RemoveE";
export * from "./UpdateE";
export * from "./CreateP";
